### ISSUE TITLE
Builds Failing on Docs.rs

### ISSUE THREAD

**Issue by lunabunn** [Lokathor/gl33#1]
I'm not sure as to what's going on, but all versions of this crate published onto crates.io are failing to build on docs.rs except for 0.0.1 (NOT 0.1.0). Downloading and building the docs locally works just fine, so seems like a docs.rs issue?

**Comment by Lokathor** [comment]
build log is here, https://docs.rs/crate/gl33/0.1.0/builds/279434

looks like I need to use the newer generator, which enables the correct language feature.

**Comment by Lokathor** [comment]
resolved in 0.1.1
